[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "OceanObserver"
authors = [{name = "Nick Mortimer", email = "nick.mortimer@csiro.au"},{name = "Paul Branson", email = "Paul.Branson@csiro.au"}]
dynamic = ["version", "description"]
